### ISSUE TITLE
Update the existing header component. 

### ISSUE THREAD

**Issue by salil-naik** [girlscript/feminist-bible-phase-2#18]
Refer to the design (Header 2 frame) and add the button and avatar to the existing header components. These two elements will be shown only when the user is logged in. Use states in React.

**Comment by abdus** [comment]
I will be working on this.

**Comment by priyanshisharma** [comment]
I want to work on this issue.

**Comment by abdus** [comment]
@salil-naik I was the first one to claim this issue /s

**Comment by salil-naik** [comment]
@abdus I appreciate your work on the header. But this issue is assigned to some other participants. 

In the frontend, the tasks are distributed beforehand to the participants so that everyone gets a fair chance to contribute.

**Comment by abdus** [comment]
> ... the tasks are distributed beforehand to the participants so ....
@salil-naik how would people know? this issue was open for around an hour or so. and AFAIK, I am also a participant.
maybe you should assign people right after creating the issue(as they already distributed somewhere else).
or at least define the ways of claiming an issue.

anyways, I won't be troubling with anymore pull-requests for front-end part.
good day.
